### ISSUE TITLE
Move the relevant `layouts` from [`hugo-agency-theme`](https://github.com/digitalcraftsman/hugo-agency-theme) to this theme

### ISSUE THREAD

**Issue by DaveParr** [satRdays/hugo-satrdays-theme#23]
Only the items that are not already present and superceded by our own current files should be copied over. 

Hugo has a 'multiple inheritance' style where the base theme, `agency`, gets sourced only when and item in the `satrdays` theme doesn't get sourced.

As per the config of the theme, we should therefore only include assets from `agency` where **_they are not already present in `satrdays`_**

**Comment by paudiaz122** [comment]
Hi! Can I do this one?

**Comment by RMHogervorst** [comment]
the following partials are not yet present in satRdays theme (don't know if we use them all though):

* _analytics/piwik.html
* head.html
* js.html
* nav.html
* services.html

**Comment by RMHogervorst** [comment]
we also don't have a layouts/404.html
