### ISSUE TITLE
[enhancement of tweetthis button in schedule]: more content of tweet based on talkXX.yaml

### ISSUE THREAD

**Issue by RMHogervorst** [satRdays/hugo-satrdays-theme#28]
Currently the tweetthis button in the schedule takes the title of the schedule component it is in:
f.i.: 'My first talk'. But we can add more or less details. This (low priority) enhancement idea proposes things that we can read from the talk.yaml files.

### Background:

The tweetthis button creates a request to twitter, using the [tweet intent api](https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/guides/web-intent) when you click the button the browser goes to your twitter feed, opens a modal and prefills that modal with the details we provide it.

### enhancements:
* Add speaker: Change content of tweet with something like: '{{ .title }} from {{ .client }}' (so it reads both .title and .client from the talk.yaml files in the data folder.
* Add more relevant details from that file
* (*) also read the speakerxx.yaml files and add twitter handle from there to relevant talk (This is probably quite difficult)

**Comment by DaveParr** [comment]
Great stuff. If the talks template was modified, we could show the speakers twitter handle in the table and source it from there at site generation stage, potentially allowing it to be more readily accessed on button press? I ask speakers for public Twitter handles on signup for promotion purposes for Cardiff events anyway (optional of course).
