### ISSUE TITLE
maybe add a 'tweet this talk' button to schedule?

### ISSUE THREAD

**Issue by RMHogervorst** [satRdays/hugo-satrdays-theme#3]
Shown here: 
https://twitter.com/robinson_es/status/1055816363506393095

tweet buttons on the schedule that pre-fill hashtags, speaker handle, and talk title!

**Comment by DaveParr** [comment]
As per discussion on https://github.com/satRdays/hugo-satrdays-theme/pull/9 I've assigned this to @RMHogervorst for completion, but in order to help me out I'd really appreciate a PR on this when it's actually ready for a merge.

**Comment by RMHogervorst** [comment]
Guess this one is done!
