### ISSUE TITLE
Fold in Angela's default images for important dates timeline

### ISSUE THREAD

**Issue by DaveParr** [satRdays/hugo-satrdays-theme#8]
Chicago 2019 used great stock images for the important events timeline that should be cc license

**Comment by RMHogervorst** [comment]
I don't know where to put the copyright information though

**Comment by DaveParr** [comment]
@angela-li I know we had a discussion on this a while back in slack which I think has now dropped off the end of our 'free' tier. Where did you source these images from again?

**Comment by angela-li** [comment]
Hm good question, I think they were from http://compfight.com/ but I might be mistaken

**Comment by DaveParr** [comment]
Theres a bit of info here: http://compfight.com/faq

Maybe a simple text file in the image folder would do? 

Would have to double check that hugo doesn't try and read it to ppoulate the image drawing when if it loops through all the items in the folder though.

**Comment by RMHogervorst** [comment]
I noticed in complete attribution of the images in the chicago config.toml
We could do the same thing
https://github.com/satRdays/chicago2019/blob/master/config.toml#L203-L234

**Comment by RMHogervorst** [comment]
Modified PR to include a text file with attributions

**Comment by angela-li** [comment]
Thanks @RMHogervorst!! And good sleuthing to find those attributions
